[theme]
# Couleur d'accent primaire pour les éléments interactifs.
primaryColor = "#E694FF"

# Couleur d'arrière-plan pour la zone de contenu principale.
backgroundColor = "#D4F6CB"

# Couleur d'arrière-plan utilisée pour la barre latérale et la plupart des widgets interactifs.
secondaryBackgroundColor = "#047C60"

# Couleur utilisée pour presque tout le texte.
textColor = "#FFF"

# Famille de polices pour tout le texte de l'application, à l'exception des blocs de code. L'un de "sans serif", "serif" ou "monospace".
# Par défaut : "sans empattement"
font = "sans serif"
