# .streamlit/secrets.toml
public_gsheets_url = "https://docs.google.com/spreadsheets/d/1Q0YKCkd7X47Iqld5dIAgKCUqEthavhE3GCLbdlDHfak/edit?usp=sharing"
public_gsheets_url2 = "https://docs.google.com/spreadsheets/d/1eQvWhRry-WCvHLZkJZ58JOXi0T--uYMDACRxYB52RU8/edit?usp=sharing"